ALTER TABLE usuario
MODIFY COLUMN nome VARCHAR(255) NOT NULL,
MODIFY COLUMN email VARCHAR(255) NOT NULL,
MODIFY COLUMN senha VARCHAR(255) NOT NULL,
MODIFY COLUMN telefone VARCHAR(20) NOT NULL,
MODIFY COLUMN data_nascimento DATE NOT NULL,
MODIFY COLUMN cpf VARCHAR(15) NOT NULL;

ALTER TABLE endereco
MODIFY COLUMN logradouro VARCHAR(255) NOT NULL,
MODIFY COLUMN cidade VARCHAR(100) NOT NULL,
MODIFY COLUMN estado VARCHAR(2) NOT NULL;

ALTER TABLE nivel_acesso
MODIFY COLUMN nome VARCHAR(50) NOT NULL